environment: 'development'

urlsModuleOptions:
  keyLength: 8

# url format redis[s]://[[username][:password]@][host][:port][/db-number]:
# example url: 'rediss://127.0.0.1:6379'
redis:
  url: 'rediss://red-cilb9hdgkuvinfjktgs0:rhsApuVTkF8TCTT1GDi4e5dxWCOIZSkP@frankfurt-redis.render.com:6379'


http:
  host: 'localhost'
  port: 3000
